name: RuboCop

on: pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: gem install rubocop rubocop-rubycw --no-document
    - name: Run RuboCop
      shell: bash
      run: |
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
        rubocop | ruby -pe 'sub(/^(.+):(\d+):(\d+): (.): (.+)$/, %q{::error file=\1,line=\2,col=\3::\5})'
